# Generated by Django 3.2.7 on 2021-10-04 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strategify', '0002_auto_20210929_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
